[project]
name = "download-mp4"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
	"dramatiq[rabbitmq]>=1.17.0",
	"httpx>=0.27.0",
	"loguru>=0.7.2",
	"pydantic>=2.7.0",
	"pydantic-settings>=2.2.1",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
