[project]
name = "video-compositor"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
	"dramatiq[rabbitmq]>=2.0.1",
	"loguru>=0.7.2",
	"pydantic>=2.7.0",
	"pydantic-settings>=2.2.1",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
