[project]
name = "storage-uploader"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
	"dramatiq==2.0.1",
	"loguru==0.7.3",
	"pika==1.3.2",
	"pydantic-settings>=2.6.1,<3.0.0",
	"requests>=2.32.0,<3.0.0",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
